eCommerce/cart/urls.py
from django.contrib import admin
from django.urls import path , include

from django.conf import settings
from django.conf.urls.static import static

from .views import *

app_name = "home"
urlpatterns = [
    path("",HomeView.as_view() , name = 'home'),
    path("product/<slug>", ProductDetailView.as_view(), name='product'),

    path("main/", main, name='main'),
    path("createproduct/", createProduct, name='createproduct'),
    path("products/", allProducts, name='products'),
    path("updateproduct/<slug>/", updateProduct, name='updateproduct'),
    path("deleteproduct/<slug>/", deleteProduct, name='deleteproduct'),
    
    path("createcategory/", createCategory, name='createcategory'),
    path("updatecategory/<slug>/", updateCategory, name='updatecategory'),
    path("deletecategory/<slug>/", deleteCategory, name='deletecategory'),

    path("cart/", cart, name='cart'),
    path("updateitem/", updateItem, name='updateitem'),
    path("checkout/", checkout, name='checkout'),

    path("register/", registerUser, name='register'),
    path("login/", loginUser, name='login'),
    path("logout/", logoutUser, name='logout'),

    path("contact/", contact, name='contact'),
    path("messages/", allMessages, name='messages'),

    path("empty/", emptyLink, name='empty'),

]
 

eCommerce/eCommerce/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cart.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

eCommerce/cart/models.py
# Create your models here.
from django.db import models
from django.shortcuts import reverse
from django.contrib.auth.models import User
#vlaue, name
STATUS = (('In Stock', 'In Stock'),('Out of Stock', 'Out Of Stock'))
LABEL = (('New Product', 'New Product'), ('Hot Product', 'Hot Product'), ('Sale Product', 'Sale Product'))
Message = (('New','New'), ('Read','Read'))

class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    username = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.username
        
class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.CharField(max_length= 200, unique=True)
    
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=200)
    slug = models.CharField(max_length=200, unique= True)
    price = models.IntegerField()
    #default = 0 ; ????
    discounted_price = models.IntegerField(default = 0)
    description = models.TextField()
    category = models.ForeignKey(Category, on_delete = models.CASCADE)
    # brand = models.ForeignKey(Brand, on_delete= models.CASCADE)
    status = models.CharField(max_length=50, choices = STATUS)
    label = models.CharField(max_length=200, choices= LABEL, default= 'new') #or blank = True
    image = models.ImageField(null = False, blank=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.name

    def get_url(self):
        return reverse ('home:product', kwargs = {'slug': self.slug})
#        urls home vanne app ko 'product' vanne url ma jane Yo 'slug' liyera
#   'home:product' make sure there is no space inbetween

    def get_cart_url(self):
        return reverse ('home:add-to-cart', kwargs = {'slug': self.slug})

class Order(models.Model):
    customer = models.ForeignKey(User, on_delete = models.SET_NULL, blank=True, null=True)
    date_ordered = models.DateTimeField(auto_now_add=True, null=True, blank=False)
    transaction_id = models.CharField(max_length=200, null=True)
  
    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total
    
    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total

class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total

class ShippingAddress(models.Model):
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    address = models.CharField(max_length=200, null=True)
    city = models.CharField(max_length=200, null=True)
    state = models.CharField(max_length=200, null=True)
    zipcode = models.CharField(max_length=200, null=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address

class Contact(models.Model):
    name = models.CharField(max_length= 200)
    email = models.CharField(max_length= 100)
    phone = models.CharField(max_length = 20 , null = True, blank = False)
    address = models.CharField(max_length = 100, null = True, blank = False )
    street = models.CharField(max_length=100,null = True, blank = False)
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.name

class ContactUs(models.Model):
    name= models.CharField(max_length=150)
    email = models.CharField(max_length=250)
    subject = models.CharField(max_length=550)
    message = models.TextField(null=True)
    label = models.CharField(max_length=200, choices= Message, default= 'New')
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.name

eCommerce/cart/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import User
from django import forms
from .models import *

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'

class CheckoutForm(forms.ModelForm):
    class Meta:
        model = ShippingAddress
        fields = '__all__'

eCommerce/cart/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import View

from pip._vendor.requests import post
from django.http import JsonResponse
import json

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from .forms import *
from .models import *
from .decorators import *


class BaseView(View):
    views = {}


class HomeView(BaseView):
    def get(self, request):
        self.views['new_products'] = Product.objects.filter(label="New Product")[
            0:8]
        self.views['sale'] = Product.objects.filter(
            label="Sale Product")[0:3]
        # self.views['contact'] = Contact.objects.all()
        self.views['categories'] = Category.objects.all()

        return render(request, 'index.html', self.views)


class ProductDetailView(BaseView):
    def get(self, request, slug):
        self.views['product_detail'] = Product.objects.filter(
            slug=slug)

        return render(request, 'productdetail.html', self.views)


def allProducts(request):
    allproduct = Product.objects.all()
    context = {
        'allproduct': allproduct,
    }
    return render(request, 'allproduct.html', context)

# --------------------------------------------------------------------------------CART


@login_required(login_url='/login')
def cart(request):
    if request.user.is_authenticated:
        customer = request.user   
        orders = Order.objects.filter(customer=customer)
        items = []
        total = 0
        cart_items = 0
        for order in orders:
            itemlist = OrderItem.objects.filter(order=order)
            for item in itemlist:
                total = total + item.product.price * item.quantity
                cart_items = cart_items + 1
                items.append(item)
 
        print(orders)
        print(items)
        order = {'get_cart_total': total, 'get_cart_items': cart_items}
        context = {'items': items, 'order': order, }
        return render(request, 'cart.html', context)
    else:
        items = []
        order = {'get_cart_total': 0, 'get_cart_items': 0}
        context = {'items': items, 'order': order, }
        return render(request, 'cart.html', context)


@login_required(login_url='/login')
def updateItem(request):
    data = json.loads(request.body)
    productId = data['productId']
    action = data['action']
    print('productId:', productId)
    print('action:', action)

    customer = request.user
    product = Product.objects.get(id=productId)
    order, created = Order.objects.get_or_create(customer=customer)
    orderItem, created = OrderItem.objects.get_or_create(
        order=order, product=product)

    if action == 'add':
        orderItem.quantity = (orderItem.quantity+1)
    elif action == 'remove':
        orderItem.quantity = (orderItem.quantity - 1)

    orderItem.save()

    if orderItem.quantity <= 0:
        orderItem.delete()

    return JsonResponse('Item was added', safe=False)


@login_required(login_url='/login')
def checkout(request):
    context = {}
    if request.method == "POST":
        # yo request vaneko chai Form ma vako input tag ko name
        address = request.POST['address']
        city = request.POST['city']
        state = request.POST['state']
        zipcode = request.POST['zipcode']

        customer = request.user
        order= Order.objects.get(customer=customer)

       
        data = ShippingAddress.objects.create(
            # models' field name = vairable
            order = order,
            address=address,
            city=city,
            state=state,
            zipcode=zipcode,
        )
        data.save()
        context['success'] = "Order Confirm"

    # yo objects vanna khojeko, database ko 'row'

    return render(request, 'checkout.html', context)


# ---------------------------------------------------------------------------Admin Dashboard

@login_required(login_url='/login')
@allowed_users(allowed_roles=['admin', ])
def main(request):
    ttl_prd = Product.objects.all()
    ttl_cat = Category.objects.all()

    messages = ContactUs.objects.all()[0:3]
    context = {
        'ttl_prd': ttl_prd,
        'ttl_cat': ttl_cat,
        'messages': messages,
    }
    return render(request, 'admindash.html', context)


@login_required(login_url='/login')
def createProduct(request):
    form = ProductForm()
    if request.method == "POST":
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('/main')
    context = {
        'form': ProductForm,
    }
    return render(request, 'createproduct.html', context)


@login_required(login_url='/login')
def updateProduct(request, slug):
    data = Product.objects.get(slug=slug)
    form = ProductForm(instance=data)

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=data)
        if form.is_valid():
            form.save()
            return redirect('/main')

    context = {
        'form': form,
    }

    return render(request, 'createproduct.html', context)


@login_required(login_url='/login')
def deleteProduct(request, slug):
    data = Product.objects.get(slug=slug)
    if request.method == "POST":
        data.delete()
        return redirect('/main')

    context = {
        'product': data,
    }

    return render(request, 'deleteproduct.html', context)


def allMessages(request):
    allmsg = ContactUs.objects.all()
    context = {
        'messages': allmsg,
    }
    return render(request, 'allmsg.html', context)

# ---------------------------------------------------------------------------CATEGORY CRUD

@login_required(login_url='/login')
def createCategory(request):
    if request.method == "POST":
        catform = CategoryForm(request.POST)
        if catform.is_valid():
            catform.save()
            return redirect('/main')
    context = {
        'catform': CategoryForm,
    }
    return render(request, 'createcategory.html', context)


@login_required(login_url='/login')
def updateCategory(request, slug):
    catdata = Category.objects.get(slug=slug)
    catform = CategoryForm(instance=catdata)

    if request.method == 'POST':
        catform = CategoryForm(request.POST, instance=catdata)
        if catform.is_valid():
            catform.save()
            return redirect('/main')

    context = {
        'catform': catform,
    }

    return render(request, 'createcategory.html', context)


@login_required(login_url='/login')
def deleteCategory(request, slug):
    catdata = Category.objects.get(slug=slug)
    if request.method == "POST":
        catdata.delete()
        return redirect('/main')

    context = {
        'category': catdata,
    }

    return render(request, 'deletecategory.html', context)

# ---------------------------------------------------------------------------LOGIN CRUD


@unauthenticated_user
def registerUser(request):
    form = CreateUserForm()
    if request.method == "POST":
        form = CreateUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            customer = Customer(user=user, username=username, email=user.email)

            messages.success(request, 'Account Was Created For ' + username)
            return redirect('/login')

    context = {'form': form}

    return render(request, 'registration.html', context)


@unauthenticated_user
def loginUser(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('/')
        else:
            messages.info(request, 'Username or Password Is Incorrect')

    context = {}
    return render(request, 'login.html', context)


def logoutUser(request):
    logout(request)
    return redirect('/')

# -------------------------------------------------------------Contact page


def contact(request):
    context = {}
    if request.method == "POST":
        # yo request vaneko chai Form ma vako input tag ko name
        name = request.POST['name']
        email = request.POST['email']
        subject = request.POST['subject']
        message = request.POST['message']

        data = ContactUs.objects.create(
            # models' field name = vairable
            name= name,
            email= email,
            subject= subject,
            message= message
        )
        data.save()
        context['success'] = "Your Message Was Sent"


    context['contact'] = Contact.objects.all()
    # yo objects vanna khojeko, database ko 'row'

    return render(request, 'contact.html', context)

# ---------------------------------------------------------------Empty Page

def emptyLink(request):
    return render(request, 'empty.html')

eCommerce/templates/admindash.html
{%  extends 'adminmain.html' %}

{% block content %}



<br>
<div class="container-fluid">
    <div class="row">
        <div class="rowcontainer col-md-12">
            <div class="card card-body">
                <a class="btn btn-sm btn-block add_btn" href="/messages">View All Messages</a>
                <table class="table table-md">
                    <tr>
                        <th>Sender</th>
                        <th>Label</th>
                        <th>Date Added</th>
                        <th>Email</th>
                        <th>Subject</th>
                        <th>Message</th>
                    </tr>
                    {%for msg in messages%}
                    <tr>
                        <td>{{msg.name}}</td>
                        <td>{{msg.label}}</td>
                        <td>{{msg.date_created}}</td>
                        <td>{{msg.email}}</td>
                        <td>{{msg.subject}}</td>
                        <td>{{msg.message}}</td>
                        
                    </tr>
                    {%endfor%}    
            
                </table>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="rowcontainer col-md-5">
            <div class="card card-body">
                <a class="btn btn-sm btn-block add_btn" href="/createcategory">Add Category</a>
                <table class="table table-md">
                    <tr>
                        <th>Category</th>
                        <th>Date Added</th>
                    </tr>
                    {%for category in ttl_cat%}
                    <tr>
                        <td>{{category.name}}</td>
                        <td>{{category.date_created}}</td>

                        <td><a class="btn btn-sm btn-info" href="{% url 'home:updatecategory' category.slug %}">Update</a></td>
                        <td><a class="btn btn-sm btn-danger" href="{% url 'home:deletecategory' category.slug %}">Delete</a></td>
                    </tr>
                    {%endfor%}    
            
                </table>
            </div>
        </div>

        <div class="rowcontainer col-md-7">
            <div class="card card-body">
                <a class="btn btn-sm btn-block add_btn" href="/createproduct">Add Product</a>
                <table class="table table-md">
                    <tr>
                        <th>Product</th>
                        <th>Price</th>
                        <th>Date Added</th>
                        <th>Status</th>
                        <th>Label</th>
                        <th>Update</th>
                        <th>Remove</th>
                    </tr>
                    {%for product in ttl_prd%}
                    <tr>
                        <td>{{product.name}}</td>
                        <td>{{product.price}}</td>
                        <td>{{product.date_created}}</td>
                        <td>{{product.status}}</td>
                        <td>{{product.label}}</td>

                        <td><a class="btn btn-sm btn-info" href="{% url 'home:updateproduct' product.slug %}">Update</a></td>
                        <td><a class="btn btn-sm btn-danger" href="{% url 'home:deleteproduct' product.slug %}">Delete</a></td>
                    </tr>
                    {%endfor%}    
                </table>
            </div>
        </div> 
    </div>
   
</div>


{% endblock %}

eCommerce/templates/adminmain.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>{%block title%}Admin{%endblock%}</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

	<link rel="stylesheet" type="text/css" href="{% static 'css/adminmain.css' %}">

</head>
<body>
	{%  include 'adminnav.html' %}
	<div class="container-fluid">
	{% block content %}



	{% endblock %}
    </div>
	<hr>

	
</body>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>

eCommerce/templates/adminnav.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
        <!-- <li class="nav-item active">
            <a class="nav-link" href="/main">DASHBOARD</a>
          </li>
       <li class="nav-item">
        <a class="nav-link" href="#">Products</a>
      </li> --> 
      <li class="nav-item active"><p>Hello, {{request.user}}</p></li>
      <li class="nav-item"><a class="btn btn-sm btn-danger" href="/logout">Logout</a></li>
    </ul>
   
    
  </div>
</nav>

eCommerce/templates/allmsg.html
{%  extends 'adminmain.html' %}

{% block content %}



<br>
<div class="container-fluid">
    <div class="row">
        <div class="rowcontainer col-md-12">
            <div class="card card-body">
                <a class="btn btn-sm btn-block add_btn" href="/main">Return To Home</a>
                <table class="table table-md">
                    <tr>
                        <th>Sender</th>
                        <th>Label</th>
                        <th>Date Added</th>
                        <th>Email</th>
                        <th>Subject</th>
                        <th>Message</th>
                    </tr>
                    {%for msg in messages%}
                    <tr>
                        <td>{{msg.name}}</td>
                        <td>{{msg.label}}</td>
                        <td>{{msg.date_created}}</td>
                        <td>{{msg.email}}</td>
                        <td>{{msg.subject}}</td>
                        <td>{{msg.message}}</td>
                        
                    </tr>
                    {%endfor%}    
            
                </table>
            </div>
        </div>
    </div>
</div>

{%endblock%}

eCommerce/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{%block title%}Cart{%endblock%}
{% block content %}
<html lang="en">

<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css"
		integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css"
		integrity="sha512-PgQMlq+nqFLV4ylk1gwUOgm6CtIIXkKwaIHp/PAIWHzig/lKZSEGKEysh0TCVbHJXCLN7WetD8TFecIky75ZfQ=="
		crossorigin="anonymous" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/cartmain.css' %}">

</head>

<body class="bg-light">
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-12 col-lg-8 col-11 mx-auto mb-lg-0 mb-5 shadow">
				<div class="row gx-3">
						{% for item in items %}
						<div class="card p-4">
							<div class="row">
								<!-- cart images div -->
								<div
									class="col-md-5 col-11 mx-auto bg-light d-flex justify-content-center align-items-center shadow product_img">
									<img src="{{item.product.image.url}}" class="img-fluid"
										alt="{{item.product.description}}">
								</div>

								<!-- cart product details -->
								<div class="col-md-7 col-11 mx-auto px-4 mt-2">
									<div class="row">
										<!-- product name  -->
										<div class="col-6 card-title">
											<h1 class="mb-4 product_name">{{item.product.name}}</h1>
											<p class="mb-2 product-description">{{item.product.description}}</p>

										</div>
										<!-- quantity inc dec -->
										<div class="col-6">

											<p class="quantity">{{item.quantity}}</p>
											<div class="quantity">
												<img data-product={{item.product.id}} data-action="add"
													src="{%static 'img/arrow-up.png'%}"
													class="chng-quantity update-cart">

												<img data-product={{item.product.id}} data-action="remove"
													src="{%static 'img/arrow-down.png'%}"
													class="chng-quantity update-cart">
											</div>
										</div>


									</div>
									<!-- //remover move and price -->
									<div class="row">
										<div class="col-5 d-flex justify-content-end price_money">
											<h4>$<span id="itemval">{{item.product.price|floatformat:2}}</span></h4>

										</div>

										

									</div>
								</div>
							</div>

						</div>
						{% endfor %}
					
				</div>
			</div>

			<div class="col-md-12 col-lg-4 col-11 mx-auto mt-lg-0 mt-md-5">
				<div class="right_side p-3 shadow bg-white">
					<h2 class="product_name mb-5">The Total Amount Of</h2>
					<div class="price_indiv d-flex justify-content-between">
						<p>Total Items</p>
						<p><span id="shipping_charge">{{order.get_cart_items}}</span></p>
					</div>
					<div class="price_indiv d-flex justify-content-between">
						<p>Product amount</p>
						<p>$<span id="product_total_amt">{{order.get_cart_total}}</span></p>
					</div>
					
					<hr />
					<div class="total-amt d-flex justify-content-between font-weight-bold">
						<p>Grand total: </p>
						<p>$<span id="total_cart_amt">{{order.get_cart_total}}</span></p>
					</div>
					<button type="button" class="btn btn-outline-danger btn-lg">
						<a href = "/checkout" class="view">
							<span>Checkout</span>
						</a>
					</button>
				</div>

		</div>
	</div>


	<!-- Optional JavaScript -->
	<!-- Popper.js first, then Bootstrap JS -->
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
		integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
	</script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js"
		integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/" crossorigin="anonymous">
	</script>


</body>

</html>
{%endblock%}

eCommerce/templates/createcategory.html
{% load static %}

<!DOCTYPE html>
<html>
    
<head>
	<title>Create Category</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

    <!--registration stylesheet-->
    <link href="{% static 'css/createcategory.css' %}" rel="stylesheet">
</head>

<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">Category</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<form method="POST">
                        {%csrf_token%}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text">Category Name</span>
							</div>
							{{catform.name}}
							<!-- <input type="text" name="username" placeholder="Category Name"> -->
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text">Slug</span>
							</div>
							{{catform.slug}}
							<!-- <input type="email" name="email" placeholder="Email"> -->
						</div>
						


				   		<div class="d-flex justify-content-center mt-3 save_container">
				 			<input class="btn save_btn" type="submit" value="Save Category">
				   		</div>
						<div class="d-flex justify-content-center mt-3 save_container">
							<a class="btn home_btn" href="{% url 'home:main' %}">Back</a>
						</div>
						
						
					</form>
					

				</div>
			</div>
		</div>
	</div>

</body>
</html>

eCommerce/templates/deletemsg.html
{%  extends 'adminmain.html' %}
{% load static %}
{%block title%}Delete Message{%endblock%}
{% block content %}

<br>
<div class="row">
	<div class="col-md-6">
		<div class="card card-body">

			<p>Are you sure you want to delete "{{messages}}"?</p>

			<form action="{% url 'home:deletemessage' messsages.subject  %}" method="POST">
				
				{% csrf_token %}
				<a class="btn btn-warning" href="{% url 'home:main' %}">Cancel</a>

				<input class="btn btn-danger" type="submit" name="Confirm">
			</form>
		</div>
	</div>
</div>

{% endblock %}

eCommerce/templates/empty.html
{%load static%}

{%block content%}

<div class="container-fluid">
    <div class="row">
        <h1>Future Updates Comming Soon</h1>
    </div>
</div>
{%endblock%}